on:
  workflow_dispatch:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      image-tag:
        required: true
        type: string
name: cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Echo
        run: echo "CD... image-tag ${{ inputs.image-tag }}"

      # TODO:
      # Configure dynamic credentials to AWS, check out the action: aws-actions/configure-aws-credentials

      # Deploy the ECS cluster using the pre-build template (templates/cluster), check this action for inspiration: aws-actions/aws-cloudformation-github-deploy

      # Update ECS task definition with the new image id / tag, check this action for idea: aws-actions/amazon-ecs-render-task-definition

      # Deploy the new ECS task based on the new ECS task definition, check this action for idea: aws-actions/amazon-ecs-deploy-task-definition

      # Get the Amplify app URL via ECS service elastic load balancer , create summary output

      # Deploy additional guardrails, such as AWS Security Hub (https://aws.amazon.com/security-hub/) and the conformance pack (https://docs.aws.amazon.com/config/latest/developerguide/conformancepack-sample-templates.html)

      # Deploy web application firewalls and AWS Managed rules (https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups.html)