on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'prod'
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
      # image tag
      image-tag:
        required: true
        type: string
name: cd

jobs:
  auth:
    permissions:
      id-token: write # need this for OIDC
    uses: ./.github/workflows/auth.yml
    with:
      env: dev
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: auth
        uses: ./.github/workflows/auth.yml
      - name: Echo
        run: echo "CD..."