on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        default: 'prod'
      working-directory:
        required: false
        type: string
        default: '.'
      image-tag:
        required: true
        type: string
name: cd

jobs:
  auth:
    permissions:
      id-token: write
    uses: ./.github/workflows/auth.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo
        run: echo "CD... image-tag ${{ inputs.image-tag }}"