on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}
name: ci

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
#      Auth example
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
#          aws-region: ${{ secrets.AWS_REGION }}        
      - name: Echo
        run: echo "CI..."    
      - name: Set image tag output
        id: set-image-tag
        run: |
          echo "IMAGE_TAG=1.0.0" >> $GITHUB_OUTPUT
