on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'dev'
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}
name: ci

jobs:

  auth:
    permissions:
      id-token: write # need this for OIDC
    uses: ./.github/workflows/auth.yml
#    with:
#      env: dev
    secrets: inherit

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: auth
        uses: ./.github/workflows/auth.yml
      - name: Echo
        run: echo "CI..."    
      - name: Set image tag output
        id: set-image-tag
        run: |
          echo "IMAGE_TAG=$1.0.0" >> $GITHUB_OUTPUT
